trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildDev
    displayName: Build package for Dev 
    jobs: 
    - job: BuildMobileApp
      steps:
        - script: echo building mobile app
          displayName: Building mobile app
        - script: echo running unit test
          displayName: Running mobile app
    - job: BuildReactApp
      steps:
        - script: echo building react app
          displayName: Building react app
        - script: echo running unit test
          displayName: Running react app
    - job: BuildNodeApp
      steps:
        - script: echo building Node app
          displayName: Building Node app
        - script: echo running unit test
          displayName: Running Node app

  - stage: BuildStaging
    dependsOn: BuildDev
    condition: succeeded('BuildDev')
    displayName: Build package for QA
    jobs: 
    - job: BuildMobileApp
      steps:
        - script: echo building mobile app
          displayName: Building mobile app
        - script: echo running unit test
          displayName: Running mobile app
    - job: BuildReactApp
      dependsOn: BuildMobileApp
      steps:
        - script: echo building react app
          displayName: Building react app
        - script: echo running unit test
          displayName: Running react app
    - job: BuildNodeApp
      dependsOn: BuildReactApp 
      steps:
        - script: echo building Node app
          displayName: Building Node app
        - script: echo running unit test
          displayName: Running Node app

    
  - stage: DeployProd
    dependsOn: 
      - BuildDev
      - BuildStaging
    condition: and(succeeded('BuildDev'),succeeded('BuildStaging'))
    displayName: Build package for Prod 
    jobs: 
    - job: BuildMobileApp
      steps:
        - script: echo building mobile app
          displayName: Building mobile app
        - script: echo running unit test
          displayName: Running mobile app
    - job: BuildReactApp
      dependsOn: BuildMobileApp
      steps:
        - script: echo building react app
          displayName: Building react app
        - script: echo running unit test
          displayName: Running react app
    - job: BuildNodeApp
      dependsOn: BuildReactApp 
      steps:
        - script: echo building Node app
          displayName: Building Node app
        - script: echo running unit test
          displayName: Running Node app