trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildDev
    displayname: Build package for Dev 
    jobs: 
    - job: BuildMobileApp
    - job: BuildReactApp
    - job: BuildNodeApp

  - stage: BuildStaging
    displayname: Build package for QA
    jobs: 
    - job: BuildMobileApp
    - job: BuildReactApp
    - job: BuildNodeApp

    
  - stage: DeployProd
    displayname: Build package for Prod 
    jobs: 
    - job: BuildMobileApp
    - job: BuildReactApp
    - job: BuildNodeApp
